# TCL File Generated by Component Editor 18.1
# Mon Jun 17 15:48:35 CEST 2019
# DO NOT MODIFY


# 
# piezo_clk_div "piezo ctl 2" v2.0
# Michael Sausmikat 2019.06.17.15:48:35
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module piezo_clk_div
# 
set_module_property DESCRIPTION ""
set_module_property NAME piezo_clk_div
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Michael Sausmikat"
set_module_property DISPLAY_NAME "piezo ctl 2"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL piezo_ctl2
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file piezo_ctl2.v VERILOG PATH piezo_ctl2.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter PULS_FREQ INTEGER 40000 ""
set_parameter_property PULS_FREQ DEFAULT_VALUE 40000
set_parameter_property PULS_FREQ DISPLAY_NAME PULS_FREQ
set_parameter_property PULS_FREQ WIDTH ""
set_parameter_property PULS_FREQ TYPE INTEGER
set_parameter_property PULS_FREQ UNITS None
set_parameter_property PULS_FREQ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PULS_FREQ DESCRIPTION ""
set_parameter_property PULS_FREQ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock ""
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit gpio_out gpio_out Output 1
add_interface_port conduit enable_in enable_in Input 1
add_interface_port conduit enable_out enable_out Output 1

