#
# This is a project Makefile.
#

PROJECT_NAME := VidorFpgaNina

# Add SPIbus library path to components
EXTRA_COMPONENT_DIRS := $(abspath component/ libary/)

include $(IDF_PATH)/make/project.mk
#include libary/interface/component.mk
